### ISSUE TITLE
Update operators to fetch the price of an asset from both chainlink and dia oracle

### ISSUE THREAD

**Issue by Robert-H-Leonard** [Robert-H-Leonard/Robert-H-Leonard#11]
Currently operators only fetch price data from chainlink. We need to update operators to also fetch price data from dia oracle.

**Comment by JdejesusIsaac** [comment]
Update the PriceFSM struct to fetch price data from both Chainlink and DIA oracles

 1. Update the PriceUpdateTaskResponse Struct:
     Ensure that the PriceUpdateTaskResponse struct can handle prices from different sources.

2. Modify the Apply Method:
    * Fetch prices from DIA oracles.
    * Append the fetched prices to the responses and submit them.
